# Generated by Django 4.1.5 on 2023-06-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="scheduled_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Started", "Started"),
                    ("Ended", "Ended"),
                    ("Cancelled", "Cancelled"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterModelTable(
            name="event",
            table="event",
        ),
        migrations.AlterModelTable(
            name="selection",
            table="selection",
        ),
        migrations.AlterModelTable(
            name="sport",
            table="sport",
        ),
    ]
