# Generated by Django 4.2.2 on 2023-06-24 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_event_scheduled_start_alter_event_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="selection",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("Unsettled", "Unsettled"),
                    ("Void", "Void"),
                    ("Lose", "Lose"),
                    ("Win", "Win"),
                ],
                max_length=255,
            ),
        ),
    ]
